# Generated by Django 6.0 on 2025-12-06 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_post_created_at_post_daraja_post_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='typework',
            new_name='region',
        ),
    ]
