# Generated by Django 6.0 on 2025-12-06 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='shartlar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='talablar',
            field=models.TextField(blank=True, null=True),
        ),
    ]
